---
abstract: 'Create detached PGP signatures for data, securely'
author:
  - 'Russ Allbery <rra@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.28'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PGP-Sign
provides:
  PGP::Sign:
    file: lib/PGP/Sign.pm
    version: '1.02'
requires:
  IPC::Run: '0'
  perl: '5.020'
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=PGP-Sign
  homepage: https://www.eyrie.org/~eagle/software/pgp-sign
  license: http://dev.perl.org/licenses/
  repository: https://github.com/rra/pgp-sign.git
version: '1.02'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
