# Workflow for GitHub Actions testing.
#
# Copyright 2020, 2022 Russ Allbery <rra@cpan.org>
#
# SPDX-License-Identifier: GPL-1.0-or-later OR Artistic-1.0-Perl

name: build

on:
  push:
    branches-ignore:
      - "debian/**"
      - "pristine-tar"
      - "ubuntu/**"
      - "upstream/**"
    tags:
      - "release/*"
  pull_request:
    branches:
      - main

jobs:
  perl:
    runs-on: ubuntu-latest

    env:
      AUTHOR_TESTING: 1

    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisites
        run: sudo apt-get install cpanminus gnupg gnupg1 hunspell

      - name: Get Perl version
        id: get-perl
        run: |
          perl -e 'print "::set-output name=version::", $^V, "\n"'

      - name: Cache Perl modules
        uses: actions/cache@v3
        with:
          path: ~/perl5
          key: ${{ runner.os }}-perl-${{ steps.get-perl.outputs.version }}-${{ hashFiles('cpanfile') }}
          restore-keys: |
            ${{ runner.os }}-perl-${{ steps.get-perl.outputs.version }}-

      - uses: perl-actions/install-with-cpanm@v1
        with:
          args: "--local-lib=~/perl5 --with-suggests --notest"
          cpanfile: "cpanfile"
          path: "/usr/bin/cpanm"
          sudo: false

      - name: Build.PL
        run: PERL5LIB=$HOME/perl5/lib/perl5 perl Build.PL

      - name: make test
        run: PERL5LIB=$HOME/perl5/lib/perl5 PATH=$HOME/perl5/bin:$PATH ./Build test
